### ISSUE TITLE
Does not work with T3 Framework

### ISSUE THREAD

**Issue by davidetaddei** [redCOMPONENT-COM/mvcOverride#2]
Hello, if enabled on a T3 Framework Joomla! installation generates the following error:

( ! ) Fatal error: Call to undefined method JViewLegacy::addViewHelperPath() in plugins/system/mvcoverride/mvcoverride.php on line 102

Is there any solution?

**Comment by shandak** [comment]
Just be sure - MVC Override plugin must be first in system plugin list. http://www.evernote.com/shard/s331/sh/e9f02398-2de3-4aa3-a941-f0020d465dbe/a344edfebf16f5ce343ac45562c2ac61
If you can able reproduce bug after fix plugin orders - i check bug.

**Comment by davidetaddei** [comment]
I updated the plugin (version 2.4.5) and it works fine, thank you anyway
